server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 47.102.100.157
sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method : POST
  appcode:
