server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    jest:
      uris: http://47.102.100.157:9200
  rabbitmq:
    host: 47.102.100.157
    username: rabbitmq
    password: rabbitmq
    virtual-host: /fengge